---
title: "Case Study 09"
author: Your Name
date: August 1, 2020
output: github_document
---
```{r}
library(sf)
library(tidyverse)
library(ggmap)
library(rnoaa)
library(spData)
data(world)
data(us_states)
```
 
 
```{r}

dataurl="https://www.ncei.noaa.gov/data/international-best-track-archive-for-climate-stewardship-ibtracs/v04r00/access/shapefile/IBTrACS.NA.list.v04r00.points.zip"
tdir=tempdir()
download.file(dataurl,destfile=file.path(tdir,"temp.zip"))
unzip(file.path(tdir,"temp.zip"),exdir = tdir)
list.files(tdir)

storm_data <- read_sf(list.files(tdir,pattern=".shp",full.names = T))
#?str(storm_data)

sf_storm <- st_as_sf(storm_data)

#colnames(storm_data)
sf_storm %>% filter(SEASON >= "1950")%>%
mutate_if(is.numeric, function(x) ifelse(x==-999.0,NA,x))%>%
mutate(decade=(floor(year/10)*10))

#?st_bbox
region = st_bbox(sf_storm)
```
 
```{r}
storm_plot <- ggplot(world)+
  geom_sf()+
  facet_wrap(~decade)+
  stat_bin2d(data=storms, aes(y=st_coordinates(storms)[,2],x=st_coordinates(storms)[,1]),bins=100)+
  scale_fill_distiller(palette="YlOrRd", trans="log", direction=-1, breaks = c(1,10,100,1000))+
  coord_sf(ylim=region[c(2,4)], xlim=region[c(1,3)])+
  axis.

plot(storm_plot) 
```
 
```{r}
us_states <- st_transform(us_states, crs = st_crs(storm_data))

us_states%>%select(state=NAME)
storm_states <- st_join(storms, states, join = st_intersects,left = F)

storm_states%>%group_by(state)%>%
summarize(storms=length(unique(NAME)))%>%
arrange(desc(storms))%>%
slice(1:5)
```
 
 