---
title: "Case Study 11"
author: Brendan Kunz
date: August 1, 2020
output: github_document
---
 
 
```{r libraries and such}
library(tidyverse)
library(spData)
library(sf)
library(lwgeom)

#I had issues with lwgeom, it seems my sf packge not being up to date caused the problem

## New Packages
library(mapview) # new package that makes easy leaflet maps
library(foreach)
library(doParallel)
registerDoParallel(4)
getDoParWorkers() # check registered cores

# go to  http://api.census.gov/data/key_signup.html and get a key, then run the line below with your key.  Don't push your key to github!
library(tidycensus)
#census_api_key("fb7a1d72931b60d4f19d95457d299f5ccfb1d66c", install = TRUE)
```
 
```{r setup}
racevars <- c(White = "P005003", 
              Black = "P005004", 
              Asian = "P005006", 
              Hispanic = "P004003")

options(tigris_use_cache = TRUE)
erie <- get_decennial(geography = "block", variables = racevars, 
                  state = "NY", county = "Erie County", geometry = TRUE,
                  summary_var = "P001001", cache_table=T)
erie <- st_crop(erie, c(xmin=-78.9,xmax=-78.85,ymin=42.888,ymax=42.92))
erie$variable <- as.factor(erie$variable)
```
 
 
 
```{r plot}
erie_all = NULL
buffalo_dots <- foreach(demo = 1:4, .combine = rbind, .packages = c("tidyverse", "sf")) %dopar% {
    #above I had issues because I forgot to add .packages, important to note for future sanity
    demographic <- levels(erie$variable)[demo]
    
    #I had issues figuring out how to place demo with levels so I had to look that up with rdocumentation
    
    erie %>%
    filter(variable == demographic)%>% 
    st_sample(size = .$value)%>%
    st_as_sf()%>%
    mutate(variable = demographic)
}

mapview(buffalo_dots, zcol = "variable", cex = 1.0, alpha = 0) #Helped by Zixuan and Hadarou

```
 

 